// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

NSObject<FlutterMessageCodec> *GlobalConfigSettingsApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  sSharedObject = [FlutterStandardMessageCodec sharedInstance];
  return sSharedObject;
}

void GlobalConfigSettingsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<GlobalConfigSettingsApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.registration_client.GlobalConfigSettingsApi.getRegistrationParams"
        binaryMessenger:binaryMessenger
        codec:GlobalConfigSettingsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getRegistrationParamsWithCompletion:)], @"GlobalConfigSettingsApi api (%@) doesn't respond to @selector(getRegistrationParamsWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getRegistrationParamsWithCompletion:^(NSDictionary<NSString *, id> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.registration_client.GlobalConfigSettingsApi.getLocalConfigurations"
        binaryMessenger:binaryMessenger
        codec:GlobalConfigSettingsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getLocalConfigurationsWithCompletion:)], @"GlobalConfigSettingsApi api (%@) doesn't respond to @selector(getLocalConfigurationsWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getLocalConfigurationsWithCompletion:^(NSDictionary<NSString *, NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.registration_client.GlobalConfigSettingsApi.getPermittedConfigurationNames"
        binaryMessenger:binaryMessenger
        codec:GlobalConfigSettingsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPermittedConfigurationNamesWithCompletion:)], @"GlobalConfigSettingsApi api (%@) doesn't respond to @selector(getPermittedConfigurationNamesWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getPermittedConfigurationNamesWithCompletion:^(NSArray<NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.registration_client.GlobalConfigSettingsApi.modifyConfigurations"
        binaryMessenger:binaryMessenger
        codec:GlobalConfigSettingsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(modifyConfigurationsLocalPreferences:completion:)], @"GlobalConfigSettingsApi api (%@) doesn't respond to @selector(modifyConfigurationsLocalPreferences:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSDictionary<NSString *, NSString *> *arg_localPreferences = GetNullableObjectAtIndex(args, 0);
        [api modifyConfigurationsLocalPreferences:arg_localPreferences completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.registration_client.GlobalConfigSettingsApi.getGpsEnableFlag"
        binaryMessenger:binaryMessenger
        codec:GlobalConfigSettingsApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getGpsEnableFlagWithCompletion:)], @"GlobalConfigSettingsApi api (%@) doesn't respond to @selector(getGpsEnableFlagWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getGpsEnableFlagWithCompletion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
