// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by GlobalConfigSettingsApi.
NSObject<FlutterMessageCodec> *GlobalConfigSettingsApiGetCodec(void);

@protocol GlobalConfigSettingsApi
- (void)getRegistrationParamsWithCompletion:(void (^)(NSDictionary<NSString *, id> *_Nullable, FlutterError *_Nullable))completion;
- (void)getLocalConfigurationsWithCompletion:(void (^)(NSDictionary<NSString *, NSString *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getPermittedConfigurationNamesWithCompletion:(void (^)(NSArray<NSString *> *_Nullable, FlutterError *_Nullable))completion;
- (void)modifyConfigurationsLocalPreferences:(NSDictionary<NSString *, NSString *> *)localPreferences completion:(void (^)(FlutterError *_Nullable))completion;
- (void)getGpsEnableFlagWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void GlobalConfigSettingsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<GlobalConfigSettingsApi> *_Nullable api);

NS_ASSUME_NONNULL_END
